/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./components/AgentCard.vue')['default']
    AuroraBackground: typeof import('./components/AuroraBackground.vue')['default']
    Button: typeof import('./components/dialog/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    ConfirmDialog: typeof import('./components/dialog/ConfirmDialog.vue')['default']
    DefaultButton: typeof import('./components/DefaultButton.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    EditOrCreateAgentDialog: typeof import('./components/dialog/EditOrCreateAgentDialog.vue')['default']
    EditOrCreateAgentFilePermissionDialog: typeof import('./components/dialog/EditOrCreateAgentFilePermissionDialog.vue')['default']
    EditOrCreateMcpServerDialog: typeof import('./components/dialog/EditOrCreateMcpServerDialog.vue')['default']
    EditOrCreateModelConnectorDialog: typeof import('./components/dialog/EditOrCreateModelConnectorDialog.vue')['default']
    FloatingPortal: typeof import('./components/notification/FloatingPortal.vue')['default']
    FlowPrimaryText: typeof import('./components/FlowPrimaryText.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    ManageAgentFilePermissionDialog: typeof import('./components/dialog/ManageAgentFilePermissionDialog.vue')['default']
    ManageAgentMcpServerDialog: typeof import('./components/dialog/ManageAgentMcpServerDialog.vue')['default']
    ManageAgentSkillDialog: typeof import('./components/dialog/ManageAgentSkillDialog.vue')['default']
    ManageAgentTaskChatHistoryDialog: typeof import('./components/dialog/ManageAgentTaskChatHistoryDialog.vue')['default']
    ManageDockerImageDialog: typeof import('./components/dialog/ManageDockerImageDialog.vue')['default']
    ManageMcpServerDialog: typeof import('./components/dialog/ManageMcpServerDialog.vue')['default']
    ManageModelConnectorDialog: typeof import('./components/dialog/ManageModelConnectorDialog.vue')['default']
    MessageDialog: typeof import('./components/dialog/MessageDialog.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NotificationContainer: typeof import('./components/notification/NotificationContainer.vue')['default']
    NotificationHost: typeof import('./components/notification/NotificationHost.vue')['default']
    NotificationItem: typeof import('./components/notification/NotificationItem.vue')['default']
    PaginatedListPanel: typeof import('./components/PaginatedListPanel.vue')['default']
    PaginationControls: typeof import('./components/PaginationControls.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    ProgressWidget: typeof import('./components/notification/ProgressWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSelector: typeof import('./components/SearchSelector.vue')['default']
    SelectOptionDialog: typeof import('./components/dialog/SelectOptionDialog.vue')['default']
    Selector: typeof import('./components/Selector.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    Task: typeof import('./components/Task.vue')['default']
    Textarea: typeof import('./components/Textarea.vue')['default']
    TextButton: typeof import('./components/TextButton.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
  }
}
