// Auto-generated by vite-plugin-dialogs — do not edit manually.

declare module "virtual:dialogs" {
	type _C = import("vue").Component;
	type _CE<T extends _C> = import("vue-component-type-helpers").ComponentExposed<T>;
	type _CP<T extends _C> = import("vue-component-type-helpers").ComponentProps<T>;
	type _DE<T> = import("./components/Dialog.vue").DialogExposed<T>;
	type _DS<T> = import("./components/Dialog.vue").DialogSettledResult<T>;
	type _DR = import("./components/Dialog.vue").DialogRejectedResult;
	type _IK = "key" | "ref" | "ref_for" | "ref_key" | "class" | "style" | `on${string}`;
	type _P<T extends _C> = Omit<_CP<T>, _IK>;
	type _V<T extends _C> = _CE<T> extends _DE<infer R> ? R : void;
	type _R<T extends _C> = _DS<_V<T>>;
	type _RN = _DR["reason"];
	type _H<T extends _C> = Promise<_R<T>> & {
		resolve(callback?: (value: _V<T> | undefined) => void): _H<T>;
		reject(callback: (reason: _RN) => void): _H<T>;
	};
	export const dialogs: {
		ConfirmDialog: (props: _P<typeof import("./components/dialog/ConfirmDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ConfirmDialog.vue")["default"]>;
		MessageDialog: (props: _P<typeof import("./components/dialog/MessageDialog.vue")["default"]>) => _H<typeof import("./components/dialog/MessageDialog.vue")["default"]>;
	};
}
