// Auto-generated by vite-plugin-dialogs — do not edit manually.

declare module "virtual:dialogs" {
	type _C = import("vue").Component;
	type _CE<T extends _C> = import("vue-component-type-helpers").ComponentExposed<T>;
	type _CP<T extends _C> = import("vue-component-type-helpers").ComponentProps<T>;
	type _DE<T> = import("./components/Dialog.vue").DialogExposed<T>;
	type _DS<T> = import("./components/Dialog.vue").DialogSettledResult<T>;
	type _DR = import("./components/Dialog.vue").DialogRejectedResult;
	type _IK = "key" | "ref" | "ref_for" | "ref_key" | "class" | "style" | `on${string}`;
	type _P<T extends _C> = Omit<_CP<T>, _IK>;
	type _RK<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K }[keyof T];
	type _A<T extends _C> = [_RK<_P<T>>] extends [never] ? [props?: _P<T>] : [props: _P<T>];
	type _V<T extends _C> = _CE<T> extends _DE<infer R> ? R : void;
	type _R<T extends _C> = _DS<_V<T>>;
	type _RN = _DR["reason"];
	type _H<T extends _C> = Promise<_R<T>> & {
		resolve(callback?: (value: _V<T> | undefined) => void): _H<T>;
		reject(callback: (reason: _RN) => void): _H<T>;
	};
	export const dialogs: {
		AgentTaskChatHistoryDialog: (...args: _A<typeof import("./components/dialog/AgentTaskChatHistoryDialog.vue")["default"]>) => _H<typeof import("./components/dialog/AgentTaskChatHistoryDialog.vue")["default"]>;
		ConfirmDialog: (...args: _A<typeof import("./components/dialog/ConfirmDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ConfirmDialog.vue")["default"]>;
		DebugDialog: (...args: _A<typeof import("./components/dialog/DebugDialog.vue")["default"]>) => _H<typeof import("./components/dialog/DebugDialog.vue")["default"]>;
		EditOrCreateAgentDialog: (...args: _A<typeof import("./components/dialog/EditOrCreateAgentDialog.vue")["default"]>) => _H<typeof import("./components/dialog/EditOrCreateAgentDialog.vue")["default"]>;
		EditOrCreateAgentFilePermissionDialog: (...args: _A<typeof import("./components/dialog/EditOrCreateAgentFilePermissionDialog.vue")["default"]>) => _H<typeof import("./components/dialog/EditOrCreateAgentFilePermissionDialog.vue")["default"]>;
		EditOrCreateMcpServerDialog: (...args: _A<typeof import("./components/dialog/EditOrCreateMcpServerDialog.vue")["default"]>) => _H<typeof import("./components/dialog/EditOrCreateMcpServerDialog.vue")["default"]>;
		EditOrCreateModelConnectorDialog: (...args: _A<typeof import("./components/dialog/EditOrCreateModelConnectorDialog.vue")["default"]>) => _H<typeof import("./components/dialog/EditOrCreateModelConnectorDialog.vue")["default"]>;
		EditOrCreateSkillDialog: (...args: _A<typeof import("./components/dialog/EditOrCreateSkillDialog.vue")["default"]>) => _H<typeof import("./components/dialog/EditOrCreateSkillDialog.vue")["default"]>;
		ManageAgentFilePermissionDialog: (...args: _A<typeof import("./components/dialog/ManageAgentFilePermissionDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageAgentFilePermissionDialog.vue")["default"]>;
		ManageAgentMcpServerDialog: (...args: _A<typeof import("./components/dialog/ManageAgentMcpServerDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageAgentMcpServerDialog.vue")["default"]>;
		ManageAgentSkillDialog: (...args: _A<typeof import("./components/dialog/ManageAgentSkillDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageAgentSkillDialog.vue")["default"]>;
		ManageAgentTaskChatHistoryDialog: (...args: _A<typeof import("./components/dialog/ManageAgentTaskChatHistoryDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageAgentTaskChatHistoryDialog.vue")["default"]>;
		ManageDockerImageDialog: (...args: _A<typeof import("./components/dialog/ManageDockerImageDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageDockerImageDialog.vue")["default"]>;
		ManageMcpServerDialog: (...args: _A<typeof import("./components/dialog/ManageMcpServerDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageMcpServerDialog.vue")["default"]>;
		ManageModelConnectorDialog: (...args: _A<typeof import("./components/dialog/ManageModelConnectorDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageModelConnectorDialog.vue")["default"]>;
		ManageSkillDialog: (...args: _A<typeof import("./components/dialog/ManageSkillDialog.vue")["default"]>) => _H<typeof import("./components/dialog/ManageSkillDialog.vue")["default"]>;
		MessageDialog: (...args: _A<typeof import("./components/dialog/MessageDialog.vue")["default"]>) => _H<typeof import("./components/dialog/MessageDialog.vue")["default"]>;
		SelectOptionDialog: (...args: _A<typeof import("./components/dialog/SelectOptionDialog.vue")["default"]>) => _H<typeof import("./components/dialog/SelectOptionDialog.vue")["default"]>;
		TextPromptDialog: (...args: _A<typeof import("./components/dialog/TextPromptDialog.vue")["default"]>) => _H<typeof import("./components/dialog/TextPromptDialog.vue")["default"]>;
	};
}
